### ISSUE TITLE
Roadmap (or todo)

### ISSUE THREAD

**Issue by ly29** [Sverchok/SverchokRedux#14]
The system is basically working now. As #7 is closed it is time to look forward a bit. All of these deserves their own issues.
- [x] Type casting #15 
- [ ] Numpy Broadcasting #15 
- [x]  properties in nodes, #17 
- [ ] mode switches and signature changes #18
- [ ] variable amount of inputs
- [x] input nodes #19 
- [ ] Node groups. think of them as functions/ blocks
- [ ] using node groups
- [ ] Nodes, mostly focusing on simple nodes of different categories.
- [ ] Refactoring of execution system
- [ ] List operations
- [ ] OpenGL viewer #16 - [Tutorial](http://ogldev.atspace.co.uk/index.html), [2](http://www.opengl-tutorial.org/)
- [ ] OpenGl data viewer #16

**Comment by ly29** [comment]
To test.
Testing, easiest is to use git and then create a symlink in the `addons` folder pointing to the `SverchokRedux` folder.
There isn't much to do yet with the system.

**Comment by nortikin** [comment]
but it not installing error in importing core/execute and compiler items from the same folder

PS

same problem was in initial Sverchok with dot import. dont remember how we solved

**Comment by nortikin** [comment]
```
  File "/home/ololo/.config/blender/2.76/scripts/addons/SverchokRedux/core/compiler.py", line 1, in <module>
    from SverchokRedux.core.execute import GraphNode
  File "/home/ololo/.config/blender/2.76/scripts/addons/SverchokRedux/core/execute.py", line 3, in <module>
    from SverchokRedux.core.compiler import create_graph
ImportError: cannot import name 'create_graph'
```

**Comment by nortikin** [comment]
maybe

```
sys.modules["SverchokRedux"] = sys.modules[__name__]
```

please
register in paths

**Comment by ly29** [comment]
Ahh, will take of that, it seems does errors don't appear on reloading after doing the changes.

**Comment by ly29** [comment]
Should work now

**Comment by ly29** [comment]
I won't mess with the `sys.modules` again, I think a better distribution system is in order

**Comment by ly29** [comment]
Tried to play a bit with opengl, but all the new functions where ´´´None´´´ in the bgl module. Didn't have time to look into that...
@zeffii Any idea?

**Comment by zeffii** [comment]
I'll make time to check the bgl stuff :) haven' looked at new functions yet

**Comment by ly29** [comment]
It is nifty, you give open gl vertices either as ordered triangles or as verts and topology. From a silly amount of function calls it becomes just a few.
And then a shader programs paints it. 
We will need a good way to triangulate though.

**Comment by ly29** [comment]
And giving means passing a memory buffer in one call.

**Comment by ly29** [comment]
Oh, I just did something stupid, now the functions show up.

**Comment by zeffii** [comment]
got any code to experiment with?

**Comment by zeffii** [comment]
@ly29  i know it's probably only cosmetic.. and your code isn't in a final state but I do read the code. And am wondering: https://gist.github.com/zeffii/7979b80c1dd61d3028c3 if that might have any effect on speed

**Comment by ly29** [comment]
@zeffii 
Working on OpenGL code.

Yeah, thumbs from me about that change. Even thinking about turning it into a named tuple/class for easer use, for the links and the node. all the lookups are getting my nerves.

```
Link = namedtuple("Link", ["from_node", "from_socket", "to_node","to_socket"])
```

**Comment by ly29** [comment]
or even the shorter forms.

**Comment by zeffii** [comment]
ideasman42 expressed an unfavourable opinion about the speed and implementation of namedtuple, quite some time ago -- i'm not sure if it is relevant here: http://blenderscripting.blogspot.nl/search/label/namedtuple

**Comment by ly29** [comment]
well if turns out to be a problem we can shift it along those lines. easy enough to do, the main thing I want is the interface of not having to look up things.

```
node=nodes[name]
node["bl_idname"]
# vs
node.bl_idname
# etc
```

**Comment by zeffii** [comment]
yeah, massive headache those `"   "` all the time. I agree.

**Comment by ly29** [comment]
I tried to, but I think I get the theory of the more modern open gl but the specifics are bit new. A working piece of code would nice.
Will hold of a bit with it.

**Comment by ly29** [comment]
[Red book](http://www.ics.uci.edu/~gopi/CS211B/opengl_programming_guide_8th_edition.pdf)

**Comment by ly29** [comment]
@zeffii 

```
import bgl
bgl.glGenVertexArrays is None
```

is also true for you?

**Comment by zeffii** [comment]
```
>>> bgl.glGenVertexArrays()
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
TypeError: function takes exactly 2 arguments (0 given)
```

**Comment by zeffii** [comment]
I don't think it's supposed to have any explicit return value, except None

**Comment by zeffii** [comment]
I am interested to see what the bgl equivalent of https://gist.github.com/zeffii/131fb3a0f6fc3ca117fb is

**Comment by zeffii** [comment]
see https://github.com/Sverchok/SverchokRedux/issues/16 for bgl talk

**Comment by ly29** [comment]
A bit of a break, will be quite busy the next couple of days. Will try to advance a bit here and there anyway.

**Comment by ly29** [comment]
###Update

So right now everything is kind broken, will focus on getting it to run again with consequences of the new type system. But will be day or two before I can do that.
